name: tiler_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.910+137


environment:
  sdk: '>=3.0.0'

dependencies:
  dio: ^5.7.0
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  # intl: ^0.18.1
  intl: ^0.20.2
  json_annotation: ^4.3.0
  tuple: ^2.0.0
  uuid: ^4.5.1
  rive: ^0.13.15
  geolocator: ^13.0.1
  duration_picker:
    path: thirdParty/duration_picker
  scroll_to_index: ^3.0.1
  flutter_colorpicker: ^1.1.0
  maps_launcher: ^3.0.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  fluttertoast: ^8.1.2
  flutter_launcher_icons: ^0.14.1
  swipe_cards: ^2.0.0+1
  rename: ^3.0.2
  weekday_selector: ^1.1.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.1
  flutter_timezone: ^3.0.1
  simple_circular_progress_bar: ^1.0.2
  flutter_svg: ^2.0.9
  lottie: ^3.1.3
  scrollable_positioned_list: ^0.3.5
  fl_chart: ^0.69.0
  font_awesome_flutter: ^10.4.0
  flutter_dotenv: ^5.0.2
  change_app_package_name: ^1.1.0
  oauth2: ^2.0.2
  mockito: ^5.4.2
  shimmer: ^3.0.0
  freezed: ^2.4.6
  sealed_unions: ^3.0.3+1
  sealed_flutter_bloc: ^8.0.1
  url_launcher: ^6.2.3
  # flutter_web_browser: "^0.17.1"
  path_provider: ^2.1.3
  webview_flutter: ^4.7.0
  logger: ^2.4.0
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  onesignal_flutter: ^5.3.0
  secure_dotenv: ^1.0.0
  shared_preferences: ^2.2.3
  dotted_line: ^3.2.2
  timelines: ^0.1.0
  table_calendar: ^3.0.9
  bloc_concurrency: ^0.2.5
  emoji_regex: ^0.0.5
  carousel_slider: ^5.0.0
  go_router: ^14.3.0
  app_links: ^6.3.2
  appinio_swiper: ^2.1.1
  cancelable: ^4.2.1
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.1.0
  flutter_slidable: ^3.1.2
  toggle_switch: ^2.3.0
  video_player: ^2.8.0

dev_dependencies:
  build_runner: ^2.4.5
  secure_dotenv_generator: ^1.0.1
  # flutter_test:
  #   sdk: flutter
  json_serializable: ^6.0.1
  flutter_spinkit: ^5.1.0
# dependency_overrides:
#   intl: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/images/crescent_moon.png
    - assets/images/person_in_bed.png
    - assets/images/umbrella_on_ground.png
    - assets/images/bath.png
    - assets/images/person_in_lotus_position.png
    - assets/images/pinched_fingers.png
    - assets/images/move_forward.png
    - assets/images/tiler_logo_black.png
    - assets/images/wire_tilerLogo_BlueBottom.png
    - assets/images/wire_tilerLogo_RedBottom.png
    - assets/images/tiler_logo_white.png
    - assets/images/tiler_logo_white_text.png
    - assets/images/binocular.png
    - assets/images/regenerativeArt/pictimely_design_a_photo_of_someone_going_on_relaxing_walk_b08a6746-c6f7-4937-86fa-445978011119.png
    - assets/images/regenerativeArt/pictimely_decorate_a_room_05c28f1e-30fb-44f9-9738-30fe5decab93.png
    - assets/images/regenerativeArt/pictimely_design_a_photo_of_diverse_people_doing_laundry_f83ffa56-27d2-4556-9bbb-175a92ec9b85.png
    - assets/images/regenerativeArt/pictimely_design_a_photo_of_someone_meeting_up_with_friends_fcf525d6-df39-4b54-887d-fc5afd8c1caa.png
    - assets/images/regenerativeArt/pictimely_design_a_photo_of_someone_working_on_their_home_89d45464-6ce9-4623-b0c4-dcbe9bee8a96.png
    - assets/images/regenerativeArt/cleanup_kitchen_prep_7fd5f130-8833-42be-be26-faf4b0110b2f_3.png
    - assets/images/regenerativeArt/deep_work_81053022-ead4-4edc-b689-a17a294c420d_3.png
    - assets/images/regenerativeArt/deep_work_aa3ab045-791b-4d59-be21-546c08bc554f_1.png
    - assets/images/regenerativeArt/plan_trip_2dde37b4-6596-42c3-adc0-c8daf853c4ed_0.png
    - assets/images/regenerativeArt/public_transit_2dde37b4-6596-42c3-adc0-c8daf853c4ed_3.png
    - assets/images/regenerativeArt/run_workout_a94bbb89-2f18-47fc-8280-7bf2634259da_2.png
    - assets/images/regenerativeArt/work_out_run_a94bbb89-2f18-47fc-8280-7bf2634259da_1.png
    - assets/images/regenerativeArt/workout_meditate_e77fbb2a-88b4-4c65-ac6b-c457145336d6_1.png
    - assets/images/regenerativeArt/workout_meditate_e77fbb2a-88b4-4c65-ac6b-c457145336d6_3.png
    - assets/rive/
    - assets/lottie/blackCars.json
    - assets/lottie/whiteCars.json
    - assets/lottie/redCars.json
    - assets/lottie/red-bicycle.json
    - assets/lottie/black-bicycle.json
    - assets/lottie/tiler-evaluating-card-swap.json
    - assets/lottie/abstract-waves-circles.json
    - assets/lottie/abstract-waves-lines.json
    - assets/lottie/abstract-waves-narrow-lines.json
    - assets/lottie/car-on-the-road.json
    - assets/lottie/Wavy-Line-Swoosh.json
    - assets/images/iconScout/block.svg
    - assets/images/iconScout/deadline.svg
    - assets/images/iconScout/notes.svg
    - assets/images/iconScout/chart.svg
    - assets/images/iconScout/pie-chart.svg
    - assets/images/iconScout/drive-time.svg
    - assets/images/iconScout/loading-red.json
    - assets/images/iconScout/door-open.svg
    - assets/images/iconScout/login.svg
    - assets/images/iconScout/logout.svg
    - assets/icons/svg/google-outline---filled(24x24)@1x.svg
    - assets/icons/settings/
    - assets/icons/vibeChat/
    - assets/videos/
  generate: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Black.ttf
        - asset: assets/fonts/Rubik/static/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/static/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Light.ttf
        - asset: assets/fonts/Rubik/static/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/static/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/static/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik/static/Rubik-SemiBoldItalic.ttf
          weight: 700
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
